### ISSUE TITLE
Support Bad Gateway

### ISSUE THREAD

**Issue by emb03** [tyler36/ddev-storybook#1]
I added the ddev-storybook addon, and when I run `ddev storybook` I get the error bad gateway. The port is not being used by anything else. 

When I run `ddev storybook -s` I get this: (not sure this is an addon issue).

> Error: 
> You installed esbuild for another platform than the one you're currently using.
> This won't work because esbuild is written with native code and needs to
> install a platform-specific binary executable.
> 
> Specifically the "@esbuild/darwin-arm64" package is present but this platform
> needs the "@esbuild/linux-arm64" package instead. People often get into this
> situation by installing esbuild on Windows or macOS and copying "node_modules"
> into a Docker image that runs Linux, or by copying "node_modules" between
> Windows and WSL environments.
> 
> If you are installing with npm, you can try not copying the "node_modules"
> directory when you copy the files over, and running "npm ci" or "npm install"
> on the destination platform after the copy. Or you could consider using yarn
> instead of npm which has built-in support for installing a package on multiple
> platforms simultaneously.
> 
> If you are installing with yarn, you can try listing both this platform and the
> other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
> feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
> Keep in mind that this means multiple copies of esbuild will be present.
> 
> Another alternative is to use the "esbuild-wasm" package instead, which works
> the same way on all platforms. But it comes with a heavy performance cost and
> can sometimes be 10x slower than the "esbuild" package, so you may also not
> want to do that.`

**Comment by tyler36** [comment]
I think there's something up with your config.
This addon merely exposes the port and and offers a helper command. It doesn't "know" anything about storybook.
