### ISSUE TITLE
Unable to Install Storybook Following Default Steps

### ISSUE THREAD

**Issue by aXb0t** [tyler36/ddev-storybook#12]
This is a follow up issue to #9, where I offered to provide steps to reproduce the issue. 

Because I am attempting to use this add-on along with DDEV to learn Storybook, there is a good chance it is my inexperience in configuring Storybook that is causing the issue.

**Basic steps are:**

- Set up minimal, default DDEV php project
- Install this add-on as instructed
- Run the command to install Storybook as instructed 
- Observe spawn xdg-open ENOENT errors

**Detailed steps:**

_Developer skills:_
PHP: 8/10
DDEV: 8/10
Storybook: 1/10

Operating System: Pop!_OS 22.04 LTS
Kernel: Linux 6.9.3-76060903-generic
Architecture: x86-64

**Start DDEV project**
- ddev config, accept all defaults
- ddev start
- 
**Install addon and restart ddev**
- ddev get tyler36/ddev-storybook
- ddev restart

**Install storybook if you haven't already...**
- ddev exec npx storybook@latest init

```
Need to install the following packages:
storybook@8.3.6
Ok to proceed? (y) y
```

```
   You can specify a project type explicitly via `storybook init --type <type>`, see our docs on how to configure Storybook for your framework: https://storybook.js.org/docs/react/get-started/install
? Do you want to manually choose a Storybook project type to install? › (y/N)
y
```

**Select**
- React
- Webpack 5

**Observe error message:**
```
/var/www/html/node_modules/storybook/bin/index.cjs:23
  throw error;
  ^
Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:6006/' ]
}
```

**Additional Observations**

Observe command `dev storybook` opens page with message "Bad Gateway"

Observe error with command: `ddev storybook -s`

```
> html@1.0.0 storybook
> storybook dev -p 6006
@storybook/core v8.3.6
info => Starting manager..
info => Starting preview..
/var/www/html/node_modules/storybook/bin/index.cjs:23
  throw error;
  ^
Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:6006/' ]
}
Node.js v20.16.0
Failed to run npm run storybook: exit status 7
```

**Comment by aXb0t** [comment]
Clarification: the pull request I sent with #9 was my likely misguided workaround to get things working on my system.

**Comment by tyler36** [comment]
Thank you for the steps.
I was able to confirm and get the same error.

I did some basic testing and it appears something breaks with the new versions.
I have an old project that has Storybook `8.0.8` installed.
This works fine, but if I run `ddev npm update`, `ddev storybook -s` breaks. Reverting to the old `package.lock` and installing older versions restores functionality.

## Test

```shell
$ ddev storybook -s
> html@1.0.0 storybook
> storybook dev -p 6006

@storybook/cli v8.0.8

info => Starting manager..
info => Starting preview..
│                                                                                          │
│   Storybook 8.0.8 for html-vite started                                                  │
│   873 ms for manager and 1.03 s for preview                                              │


$ ddev npm update
added 17 packages, removed 580 packages, changed 112 packages, and audited 279 packages in 43s


$ ddev storybook -s
> html@1.0.0 storybook
> storybook dev -p 6006

@storybook/core v8.3.6

info => Starting manager..
info => Starting preview..
/var/www/html/node_modules/storybook/bin/index.cjs:23
  throw error;
  ^

Error: spawn xdg-open ENOENT
```

**Comment by tyler36** [comment]
OK ... just looking at their GitHub and found the following related issue

https://github.com/storybookjs/storybook/issues/28772

**Comment by tyler36** [comment]
Added #13 that should fix the problem.

**Comment by aXb0t** [comment]
Will test this out later today to verify / close this issue.

Storybook bug makes perfect sense; since my Storybook skill is 1/10, I was unable to find my own solution.

**Comment by aXb0t** [comment]
TESTED: Works with an initial hiccup.

Tested with a forked release branch on my other (work) account. 

The initial install still results in the `spawn xdg-open ENOENT` error, however the Storybook server starts and runs fine afterward. 

Is there another command somewhere that would benefit from the `--no-open` flag?

Test steps:
---

ddev config
- use all defaults

ddev add-on get aberry12085/ddev-storybook (forked test release of command modifications using `-- --no-open`)

ddev restart

ddev exec npx storybook@latest init

manually select Storybook project type to install
- html
- Webpack 5

Observe initial error on `ddev exec npx storybook@latest init` command:
```
/var/www/html/node_modules/storybook/bin/index.cjs:23
  throw error;
  ^
Error: spawn xdg-open ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:6006/' ]
}
Node.js v18.20.4
```
Observe `ddev storybook -s` command successfully starts Storybook server!

**Comment by aXb0t** [comment]
Ran through the installation again and it looks like Storybook is pwning itself.

`ddev exec npx storybook@latest init` installs Storybook as it should

Storybook installer runs something like `npm run storybook dev -p 6006` automatically, causing the "Error: spawn xdg-open ENOENT" -- with the context of the [related Storybook issue](https://github.com/storybookjs/storybook/issues/28772)  -- ~~this may be affecting just my Linux systems.~~

~~I will try again on a Mac system I happen to have access to today.~~

~~I can also try installing `xdg-utils` on my Linux systems to see if that helps.~~

EDIT:
I misunderstood, it is the DDEV/Docker container that needs xdg-utils. Manually installing these in the DDEV Docker container avoids the issues altogether neatly. 

Is it possible for a DDEV add-on to include or install something like xdg-utils to the Docker container? Seems like it would cleanly solve the issue, and avoid the --no-open flag which only partially helps this add-on run cleanly.

**Comment by tyler36** [comment]
My testing show install `xdg-utils` inside the web contain worked. I did it manually via `ddev ssh`.

It's unforunate that Storybook starts its server and tries to open that page during installation. 
We could add `xdg-utils` by [customizing the docker image](https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/). This feels a little hack-y to me but perhaps its the cleaner solution.

**Comment by aXb0t** [comment]
Storybook allows install without starting the dev server: https://storybook.js.org/docs/api/cli-options#init

Adjusting the add-on documentation to `ddev exec npx storybook@latest init --no-dev` might allow the user to sidestep the initialization fault. Then the `--no-open` flags can handle the DDEV command issues.

Less work and less hacky way?

**Comment by tyler36** [comment]
Wow. Nice find. That feels much nicer.

**Comment by aXb0t** [comment]
#13 and #14 should fix this issue for me.

**Comment by tyler36** [comment]
Thank you for the updates and your work on these!
I try and merge #13 today or tomorrow.
